service: components-other-api
configValidationMode: error
deprecationNotificationMode: error

provider:
  name: aws

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi: '*'

plugins:
  - ./plugin/plugin
