service: components-api
configValidationMode: error
deprecationNotificationMode: error

provider:
  name: aws

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi: '*'

custom:
  paramfromothercomponent: ${param:fromother}
